spring:
  profiles:
    active: default
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/users?currentSchema=users_service
    port: 5432
    driver-class-name: org.postgresql.Driver
server:
  port: 82